name: Main Runner

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - user: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with: 
          python-version: "3.x"

      - name: Install dependencies
        run: | 
          python - m pip install --upgrade pip 
          pip install -r requirements.txt

      - name: Run with .env
        env: 
          BOT_SECRET: ${{secrets.BOT_SECRET}}
          BOT_TOKEN: ${{secrets.BOT_TOKEN}}